" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.vim_runtime/my_configs.vim

set runtimepath+=~/.vim_runtime
set number

source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim
try
  source ~/.vim_runtime/my_configs.vim
catch
endtry

nnoremap <leader>f :<C-f>
set relativenumber
autocmd BufEnter * if &filetype == "" | setlocal ft=text | endif
set nocp
colorscheme gruvbox
"colorscheme koehler
"colorscheme mayansmoke

set cinoptions+=L0
